default: part2

all: sample1 sample2 part1 part2

sample1:
	PART=1 python3 app.py < sample.txt
sample2:
	PART=2 python3 app.py < sample2.txt

part1:
	PART=1 python3 app.py < full.txt
part2:
	PART=2 python3 app.py < full.txt
